### ISSUE TITLE
formio js in angular showing the error like 'map of null'

### ISSUE THREAD

**Issue by DVMane** [beranradek/formio#11]
System throwing error "Can not read property 'map' of null" When user click on save button in Customer profile

**Comment by beranradek** [comment]
Hi DVMane,

since Formio library itself does not provide any JavaScript, nor for Angular, the error is maybe specific to your application. Some code in your application is apparently using variable.map(...) where the variable is not initialized to an expected object (but to null value for which "map" cannot be called). Do you have any stacktrace available?

Radek
